# Exported from Render on 2026-02-20T04:02:13Z
version: "1"
projects:
- name: Task Management API
  environments:
  - name: Development
    services:
    - type: web
      name: task-management-api
      runtime: python
      repo: https://github.com/JMooreWeb/task-management-api
      plan: free
      envVars:
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
      - key: ALGORITHM
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENV
        sync: false
      region: virginia
      buildCommand: pip install -r requirements-dev.txt
      startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
      autoDeployTrigger: commit
      rootDir: src
